### ISSUE TITLE
Archive interlok-csv-json project

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok-csv#176]
Once https://github.com/adaptris/interlok-csv/pull/175 is merged we no longer need the top level interlok-csv-json project.

- interlok-csv-json proper should be archived.
- interlok-csv-json should be removed from internal CI pipeline
- interlok-csv-json should be removed release scripts (since it will be part of interlok-csv)

**Comment by quotidian-ennui** [comment]
https://github.com/adaptris/interlok-csv/pull/175 has been merged so you should be able to action this issue.

**Comment by sebastien-belin-adp** [comment]
adaptris/interlok-csv-json ha been archived and remove from pipelines and release scripts.
